### ISSUE TITLE
「bug」点击底部图标无法跳转

### ISSUE THREAD

**Issue by xiaochopin** [crispgm/jekyll-crisp-minimalism-theme#1]
点击主页底部的`GitHub`图标无法跳转
配置文件`config.yml`中已填写用户名

**Comment by crispgm** [comment]
看起来 https://github.com/crispgm/minimal/blob/master/_includes/footer.html#L5 这里用错变量了 需要改成`{{ item.link }}`

**Comment by xiaochopin** [comment]
感谢，修改后问题解决
